### ISSUE TITLE
Unhandled exception on handler

### ISSUE THREAD

**Issue by Sacti00n** [UrekD/Telegram-To-Discord#1]
Getting this Error:

Unhandled exception on handler
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\telethon\client\updates.py", line 467, in _dispatch_update
    await callback(event)
  File "C:\Telegram-To-Discord-main\main.py", line 65, in handler
    dur = event.message.file.duration # Get duration
AttributeError: 'NoneType' object has no attribute 'duration'

**Comment by UrekD** [comment]
Hey, what version of python and telethon version are you running?

**Comment by Sacti00n** [comment]
I‘m using 3.11.1

**Comment by UrekD** [comment]
and telethon...?

**Comment by UrekD** [comment]
Check latest, I updated some distributions but it works fine with PIP packages. Looking at the log you submitted I can only guess that the Anaconda Telethon package is the issue.

**Comment by Sacti00n** [comment]
Works like a charm now, thank you :D

**Comment by UrekD** [comment]
Glad to help, if you like the repo consider leaving a star :)
