### ISSUE TITLE
User Names

### ISSUE THREAD

**Issue by ja9988** [UrekD/Telegram-To-Discord#11]
Thx, for this very useful tool.

I've been able to send messages successfully, from telegram to discord. 

And, it includes the server name, that it was sent from.

But it does not include the user that sent it.

Is there any way that in the discord server, where the tg messages are webhook'd, that it could include the tg group name & the message w/username that wrote it?

Thank you.

**Comment by UrekD** [comment]
> Thx, for this very useful tool.
> 
> I've been able to send messages successfully, from telegram to discord.
> 
> And, it includes the server name, that it was sent from.
> 
> But it does not include the user that sent it.
> 
> Is there any way that in the discord server, where the tg messages are webhook'd, that it could include the tg group name & the message w/username that wrote it?
> 
> Thank you.

Hey @ja9988 ,

Username will now be included as the webhooks username as of 6d40683, if it's available, I'm not sure how it works as sometimes it's none. 

![image](https://github.com/UrekD/Telegram-To-Discord/assets/38784343/018cc26e-7bf2-4066-b4f8-9c18d65a6e0d)
