### ISSUE TITLE
[FEATURE REQUEST] Filter word feature

### ISSUE THREAD

**Issue by papix69** [UrekD/Telegram-To-Discord#12]
Can you add a filter feature which will replace specific word to the word we want ??

**Comment by UrekD** [comment]
Hey @papix69 ,

I don't see much value in implementing this feature myself, at this moment.  
If you want to hardcode this in your script you can add something along the lines at line 64:

`msg = msg.replace("ORIGINAL", "REPLACED")`

**Comment by papix69** [comment]
Is there a way to add multiple filter words?

**Comment by UrekD** [comment]
> Is there a way to add multiple filter words?

Most likely you would need to write a function to handle that, array and loop through it replacing your list of chosen words.

**Comment by papix69** [comment]
Thanks for the info, I've added the feature. One last question can we forward different channel messages to different webhooks?

**Comment by UrekD** [comment]
To do that you would need to create an array with pairs of telegram channel and discord webhook or maybe multiple hooks, then loop over that if multiple when sending and also passing the webhook url to the send functions.
