### ISSUE TITLE
Add translation boolean

### ISSUE THREAD

**Issue by nickshanks347** [UrekD/Telegram-To-Discord#4]
I think this is great but not every message needs to be translated, so maybe add a config item in .env with a boolean value that either turns translation on or off?

**Comment by UrekD** [comment]
> I think this is great but not every message needs to be translated, so maybe add a config item in .env with a boolean value that either turns translation on or off?

Thanks for suggesting, fortunately I don't have much time to set up the bot and test, but I think it has been implemented correctly, if you would be so kind to try and report back. Changes can be found in [the new branch](https://github.com/UrekD/Telegram-To-Discord/tree/translation-toggle)

**Comment by UrekD** [comment]
Done in #5
