### ISSUE TITLE
multiple channels

### ISSUE THREAD

**Issue by Jacquesvdberg92** [UrekD/Telegram-To-Discord#6]
hello

how to have it check more than 1 telegram channel?

**Comment by UrekD** [comment]
By default it works on all channels, if you want to specify only certain channels you should be able to do it in .env, you have an example there
INPUT_CHANNELS = 13,14

**Comment by Jacquesvdberg92** [comment]
Yeah got it thanks, I was initially trying to do the "," separator in the top line.

I have one more question, I am running multiple of these bots at the same time but it seems that you cannot pull from multiple API's at the same time.
What i mean is I have one set to use my telegram API and another to use bot with the API of my friends Telegram, but it seems there is a conflict.

Thanks for the bot it works great

**Comment by UrekD** [comment]
> Yeah got it thanks, I was initially trying to do the "," separator in the top line.
> 
> I have one more question, I am running multiple of these bots at the same time but it seems that you cannot pull from multiple API's at the same time.
> What i mean is I have one set to use my telegram API and another to use bot with the API of my friends Telegram, but it seems there is a conflict.
> 
> Thanks for the bot it works great

I am unaware of what API restrictions Telegram has in place. Presuming you are running both instances on same machine, you could try running it on a different one or best seperate VM's or VPS's. What error does it throw?

**Comment by y0gurt** [comment]
I'm having issues with the multiple channels function. 

```
## Filter Channels Examples
# You can get ID's from the URL's https://web.telegram.org/
INPUT_CHANNELS = "-1001676275372"
#INPUT_CHANNELS = 13,14
#BLACKLIST = True # If true INPUT_CHANNELS act's as a blacklist instead of a whitelist

```

This is the current code I have in the .env file. If I want to add another channel ID, do I seperate it in such way 

INPUT_CHANNELS = "xxxx", "yyyy"
or have multiple input channels in such

INPUT_CHANNELS = "xxxx"
INPUT CHANNELS  = "yyyy"

thanks in advance

**Comment by UrekD** [comment]
Hey @y0gurt ,

No the input channels are excepted to be int's, in your example the input is incorrect and should be **1676275372** as -100 is [some kind of prefix ](https://stackoverflow.com/questions/33858927/how-to-obtain-the-chat-id-of-a-private-telegram-channel)I believe. I suggest using Nekogram client to get channel ID's since it clearly displays them. If that doesn't work you can link me the channel and I can check the ID.
