### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by eoghan2t9** [UrekD/Telegram-To-Discord#7]
Hi guys 

I have run this script and from what i can tell have filled in all the correct details. The script runs but wont copy anything from Telegram to Discord. My python version is 3.10 and all requirements are installed correctly but it just seems to hang here:

Started
Input channels: [xxxxxxxxxx]
Blacklist: None

Any ideas on how to debug this?

Thanks

**Comment by eoghan2t9** [comment]
just to add i have set the DLLOC option to a cache folder on my ubuntu server and the folder is empty so its not even downloading the chat images etc

**Comment by UrekD** [comment]
Hello, ensure the channels you inputted are correct, have you tried by leaving the setting commented out? That case would work on all channels you are in.

To get a debug output you can add this before line 14:
import logging
logging.basicConfig(filename='app.log', filemode='w', level=logging.DEBUG, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')  
logging.getLogger('telethon').setLevel(level=logging.DEBUG)  
logger = logging.getLogger(__name__)

**Comment by eoghan2t9** [comment]
Thanks 

I have tried commenting out the input channels and nothing changed so added the debug section and this is all I get


`2023-04-26 17:04:05,892 - telethon.network.mtprotosender - DEBUG - Encrypting 1 message(s) in 20 bytes for sending
2023-04-26 17:04:05,893 - telethon.network.mtprotosender - DEBUG - Encrypted messages put in a queue to be sent
2023-04-26 17:04:05,893 - telethon.network.mtprotosender - DEBUG - Waiting for messages to send...
2023-04-26 17:04:05,893 - telethon.extensions.messagepacker - DEBUG - Assigned msg_id = 7226390046549575816 to MsgsAck (7f453a76eb00)
2023-04-26 17:04:05,893 - telethon.network.mtprotosender - DEBUG - Encrypting 1 message(s) in 36 bytes for sending
2023-04-26 17:04:05,894 - telethon.network.mtprotosender - DEBUG - Encrypted messages put in a queue to be sent
2023-04-26 17:04:05,894 - telethon.network.mtprotosender - DEBUG - Waiting for messages to send...
2023-04-26 17:04:05,946 - telethon.network.mtprotosender - DEBUG - Handling RPC result for message 7226390046545733464
2023-04-26 17:04:05,947 - telethon.network.mtprotosender - DEBUG - Receiving items from the network...
`

And just sticks at the last line in that log

**Comment by UrekD** [comment]
> telethon.network.mtprotosender - DEBUG - Receiving items from the network...

Hey, sorry for the late reply, from my understanding this should be a connection problem to the Telegram network. Can you try using another network and another telegram account?

**Comment by eoghan2t9** [comment]
Hi apologies for my late reply lol. How do I try another network as I don't think it's an account problem?

**Comment by UrekD** [comment]
> Hi apologies for my late reply lol. How do I try another network as I don't think it's an account problem?

Hey, use another server if you have or try running it on your PC/Laptop if its not in the same network as your current server. You could use a service such as replit there is some free plan, I used hacker plan before to run it as it was free for students part of githubs  program

**Comment by eoghan2t9** [comment]
I will have a check my home server tonight and see if it works on that. The strange thing is I've tested another forwarder and it works but only seems to forward images and not text so I would love to get this going so I can forward multiple channels to one discord channel

**Comment by UrekD** [comment]
> I will have a check my home server tonight and see if it works on that. The strange thing is I've tested another forwarder and it works but only seems to forward images and not text so I would love to get this going so I can forward multiple channels to one discord channel 

Could be an issue due to python version as 3.11 had major changes I believe and you are using an older one or something changed with packages, but it worked for me last week with what's in the repo. Should really dockerize the thing..

**Comment by eoghan2t9** [comment]
Just updated python to 3.11 and not telethon won't import because python says the modules not installed when it definitely it lol. Can you guide me on getting it working via docker instead?

**Comment by UrekD** [comment]
> Just updated python to 3.11 and not telethon won't import because python says the modules not installed when it definitely it lol. Can you guide me on getting it working via docker instead?

When you change the Python version you need to install all the requirements again. If you wish to use docker the dockerfile is in the repo to build the image, that you just pass the same vars to as in .env. Tho I have not tested it as I'm not sure how to login when it's running in docker, although it should be possible.

**Comment by eoghan2t9** [comment]
I'll do some tests tonight and once I get it working via docker I'll make a guide for you 😉

**Comment by UrekD** [comment]
Hello, I'll be going ahead and closing the issue since I haven't heard back in a week. If you make a guide please make a merge request with the edits done to the readme, thank you.
